### PR TITLE
Update grid_search.py

### PR DESCRIPTION
**Pull request by Kautenja**
Fix `best_params_` not being set after a call to `fit`. This resolves issue #73

### CODE REVIEW

**Comment by srowen** [comment]
This looks like an obvious fix. The tests that are configured as of the point you opened the PR don't work anymore, but, I'm going to merge anyway. If somehow it breaks something, well, there's more to fix shortly anyway

**Comment by srowen** [comment]
Ah, no that doesn't work. Looks like we can't set this attribute as it's inherited from BaseSearchCV. Maybe someone with better knowledge of Python could propose a better way to do it, but this won't work. Reverting ...

**Comment by Kautenja** [comment]
@srowen, Polymorphism wouldn't restrict setting the `best_params_` attribute in a subclass. The only case where that would make sense is in the case of attributes or methods with a double-under (i.e., `__foo`), which are "private" to the super class. If you look at the source for [`BaseSearchCV`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/model_selection/_search.py) (line 695) `best_params_` is set once and only once in the `fit` method. This method is overridden by `GridSearchCV` with no super call, so setting the `best_params_` attribute in this method is accurate to the specification. Further, `index_` and `best_estimator_` are also set by this subclass, and are also inherited from `BaseSearchCV`, so the argument here that python's polymorphism somehow restricts usage of inherited arbitrary non-double-under attributes is disproven by counterexample. Could you elaborate as to _why_ the change does not work (i.e. stack trace, test cases that go from green to red)? My guess is that there is a different bug, or an incorrect test case.

**Comment by srowen** [comment]
I should say: I know little about Python, and am mostly trying to clean house here. I hope there's a way to do this, but, this change caused the tests to fail. Did you see the travis log? https://travis-ci.org/databricks/spark-sklearn/jobs/465359775 

```
======================================================================
ERROR: test_cv_linreg (spark_sklearn.tests.test_grid_search_2.CVTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/databricks/spark-sklearn/python/spark_sklearn/tests/test_grid_search_2.py", line 66, in test_cv_linreg
    skl_gs = grid_search.fit(X, y)
  File "/home/travis/build/databricks/spark-sklearn/python/spark_sklearn/grid_search.py", line 274, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/home/travis/build/databricks/spark-sklearn/python/spark_sklearn/grid_search.py", line 372, in _fit
    self.best_params_ = best_parameters
AttributeError: can't set attribute
```

Is there a way that would work? BTW the tests should actually pass again if you run locally with scikit 0.18 or 0.19, so should be easy to verify either way.

I'd definitely merge a change that makes this work correctly.

**Comment by srowen** [comment]
Let's move the discussion to https://github.com/databricks/spark-sklearn/issues/73 ; this does clearly seem like a problem that's popped up a few places, even if this particular change doesn't seem like it is the whole answer.

**Pull request merged**
