### PR TITLE
Download Spark from mirrors; test vs newer Spark, libs

### PR DESCRIPTION
**Pull request by srowen**
First, this changes the Spark download script to use real Apache mirrors. The cloudfront URL here only hosts up to Spark 2.2 and was abandoned years ago by upstream Spark.

This also reduces the build matrix to 3 combos:
- Python 3.6 + Spark 2.4 + scikit 0.19
- Python 3.5 + Spark 2.3 + scikit 0.18
- Python 2.7 + Spark 2.3 + scikit 0.18

Part of the reason is to simply keep up with slightly newer versions, especially of Spark.

But also because it seems like the mkl issues might be due to dependency issues in older versions. I kind of doubt this fixes _that_, but we can see, and at least this change may be otherwise useful.

### CODE REVIEW

**Comment by srowen** [comment]
That actually 'worked': https://travis-ci.org/databricks/spark-sklearn/jobs/464446776
No more mkl issues; the test failure is a -0.0 vs 0.0 comparison later in tests. WDYT?

**Comment by BenWilson2** [comment]
Are we drawing a line in the sand and not allowing for older spark version support?  Not that I have a problem with that... just curious.

**Comment by srowen** [comment]
I suppose my logic is that we can roughly follow what Spark supports. Spark 2.2 is EOL as of, oh, right about now. Python 2 is basically EOL too, but until it hurts to maintain support separately, why not keep testing it, I figure. (Maybe we discover it's a pain to release for both Python 2 and 3). The other libs don't matter as much, just trying to keep up with what seems to be a recent stable release matching platforms out there.

As a happy consequence of these changes (probably the Python lib versions), the weird MKL problem goes away and we can test again. And the rest of the build changes are to support Spark >= 2.3.

**Comment by srowen** [comment]
I fixed the test too, just a cosmetic issue in the doctest. OK to push?

**Pull request merged**
