### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by zero323**
Add Python 3 compatibility:

- use absolute imports inside spark-sklearn
- convert `zip` output to list to be able to use `len`

### CODE REVIEW

**Comment by leriomaggio** [comment]
:+1:

**Comment by nehalecky** [comment]
hey all, this looks like a helpful library. Unofortunately, we unable to explore more because our stack is based in Python 3. On that note, what's the status with this PR? Anything we can do to see it accepted and merged soon? Thanks!

**Comment by thunterdb** [comment]
@zero323 @nehalecky sorry for the delay. I finally added travis continuous integration so we can run automated tests. Would you mind modifying the `.travis.yml` file so that it also tests python 3?

```
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
...
```

**Comment by zero323** [comment]
@thunterdb Rebased, updated and pushed.

**Comment by thunterdb** [comment]
@zero323 merging, thanks!

**Comment by nehalecky** [comment]
wow, great, thanks @thunterdb, @zero323 and all!

**Comment by nehalecky** [comment]
Oh, one last question: any estimate as to when this make it to PYPI?

**Comment by thunterdb** [comment]
@nehalecky it is pushed on pypi as of a few minutes ago (release 0.1.2)

**Comment by zero323** [comment]
@thunterdb Thanks. On a side note do you have any roadmap for this project?

**Pull request merged**
